@extends('layouts.homelayout')

@section('title', 'WB-DigiTech | Privacy Policy')

@section('content')

<div class="container py-5">
    <h1 class="mb-4">Privacy Policy</h1>

    <p>
        This Privacy Policy is intended to inform you regarding the personal information that may be collected through WB-DIGITECH and how we use, share, and protect that information. By using this site, you agree to this Privacy Policy, and as such we strongly encourage our visitors to reach through this content regularly to stay informed of its contents and any changes. In the following policy, “we, us, and site” are used to refer to WB-DIGITECH.
    </p>

    <h2>Applicability of this privacy policy</h2>
    <p>
        This Privacy Policy reflects the information that is collected and shared via wbdigitech.ae. For other distribution channels (email, social media, etc.) different rules may apply.
    </p>

    <h2>Use of user information</h2>
    <p>
        In efforts to better serve your needs, WB-DIGITECH collects and stores personal information that you choose to voluntarily provide through our contact forms and other means of communication in which you provide your information. The information collected may include but is not limited to your name, email address, phone number, and resume. The website may also auto-collect information to improve your user experience including your IP address, browser type, operating system, referring URLs, and actions taken on the site. This information may be used to offer you an improved user experience, to improve our site to better serve your needs or to send periodic emails that may be relevant to your needs, and respond to inquiries, questions, and/or other requests.
    </p>

    <p>
        We value your information and protect your privacy by utilizing this information only in a way that best benefits you. WB-DIGITECH does not rent, sell, or share personal information about you with other people or non-affiliated companies without your explicit approval outside of the following purposes:
    </p>

    <ul>
        <li>To provide products or services you’ve requested</li>
        <li>To provide the information to trusted entities who work on behalf of or with WB-DIGITECH under strict confidentiality agreements in order to help us communicate with you regarding relevant offers from WB-DIGITECH and our marketing partners. These companies do not have any independent right to further share or disseminate this information</li>
        <li>To respond to subpoenas, court orders, or legal processes, to establish or exercise our legal rights or defend against legal claims</li>
        <li>To share the information in order to investigate, prevent, or take action against any illegal activities, suspected fraud, situations involving potential threats to the physical safety of any person, or as otherwise required by law</li>
        <li>To transfer information about you if WB-DIGITECH is acquired by or merged with another company</li>
    </ul>

    <h2>Secured information</h2>
    <p>
        We adopt the best industry standards for data collection, storage, processing practices, and security measures to protect you against unauthorized access, alteration, disclosure, or destruction of your personal information.
    </p>

    <h2>Cookies</h2>
    <p>
        Our site may use “cookies” to enhance and personalize your user experience. Cookies are generated by your web browser for record-keeping purposes and to track information regarding your website navigation. Permission of Cookies can be modified through your own personal settings. You may choose to set your web browser to refuse cookies or to alert you when cookies are being sent – however, doing so may limit the functionalities of the site performance. Cookies are also used for security purposes, website statistical data, pages visited, files downloaded, and user paths.
    </p>

    <h2>Links to other websites</h2>
    <p>
        In order to provide additional information or services, WB-DIGITECH may include links to external websites. Clicking on such a link will navigate you away from WB-DIGITECH site. Other site’s privacy practices may differ from our own. We do not endorse or make any representations regarding third-party websites. When clicking off the WB-DIGITECH site, we strongly encourage you to visit the other site’s Privacy Policy to ensure it meets the standards of your own personal preferences.
    </p>

    <h2>Your acceptance of these terms</h2>
    <p>
        By using this site, you signify your acceptance of this policy. If you do not agree to this policy, please do not use our site. Your continued use of the site now or following the posting of changes to this policy will be deemed as your acceptance of the site and any changes.
    </p>

    <h2>Contacting us</h2>
    <p>
        If you have any questions regarding our Terms and Conditions or your dealings with wbdigitech.ae, please contact us through our Contact Form, or with the following information:
    </p>
    <p>
        Email: <a href="mailto:info@wbdigitech.ae">info@wbdigitech.ae</a>
    </p>
</div>

@endsection
